---
- name: Copy SSH public key and set up SSH authentication
  hosts: tag.check
  become: yes

  vars:
    ansible_user: jenkins
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    
- name: Execute the copy-ssh-key.sh script
  command: /home/{{ ansible_user }}/copy-ssh-key.sh
 
