---
- name: Copy SSH public key and set up SSH authentication
  hosts: tag.check
  become: yes

  vars:
    ansible_user: jenkins
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    
  tasks:
    - name: Install Git
      apt:
        name: git
        state: present
